services:
  postgres:
    image: postgres:14
    container_name: disaster-postgres
    environment:
      POSTGRES_DB: disaster_db
      POSTGRES_USER: disaster_user
      POSTGRES_PASSWORD: disaster_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U disaster_user -d disaster_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: disaster-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: